export type TranscriptSegment = {
  text: string;
  start: number;
  duration: number;
};

export type TranscriptResult = {
  id?: string;
  videoId: string;
  videoUrl: string;
  videoTitle: string;
  channelName: string;
  thumbnail: string;
  language: string;
  selectedLanguage: string;
  isAutoGenerated: boolean;
  segmentCount: number;
  fullText: string;
  segments: TranscriptSegment[];
  createdAt?: string;
};

type ActorItem = Record<string, unknown>;

function asString(value: unknown, fallback = ''): string {
  return typeof value === 'string' ? value : fallback;
}

function asNumber(value: unknown, fallback = 0): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : fallback;
}

export function normalizeActorItem(item: ActorItem): TranscriptResult {
  const segments = Array.isArray(item.segments)
    ? item.segments.map((segment) => {
        const raw = segment as ActorItem;
        return {
          text: asString(raw.text),
          start: asNumber(raw.start),
          duration: asNumber(raw.duration)
        };
      })
    : [];

  const fullText = asString(item.fullText, segments.map((segment) => segment.text).join(' ').trim());

  return {
    videoId: asString(item.videoId),
    videoUrl: asString(item.videoUrl),
    videoTitle: asString(item.videoTitle, 'Untitled video'),
    channelName: asString(item.channelName, 'Unknown channel'),
    thumbnail: asString(item.thumbnail),
    language: asString(item.language, 'en'),
    selectedLanguage: asString(item.selectedLanguage, asString(item.language, 'en')),
    isAutoGenerated: Boolean(item.isAutoGenerated),
    segmentCount: asNumber(item.segmentCount, segments.length),
    fullText,
    segments
  };
}

export function formatTime(totalSeconds: number): string {
  const safeSeconds = Math.max(0, Math.floor(totalSeconds));
  const minutes = Math.floor(safeSeconds / 60);
  const seconds = safeSeconds % 60;
  return `${minutes}:${seconds.toString().padStart(2, '0')}`;
}
