import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import type { Session, User } from '@supabase/supabase-js';
import {
  AlertCircle,
  ArrowRight,
  BadgeCheck,
  Check,
  Clock3,
  Copy,
  ExternalLink,
  History,
  Loader2,
  LogOut,
  PanelRight,
  Play,
  ReceiptText,
  Settings2,
  ShieldCheck,
  Sparkles,
  UserRound,
  X
} from 'lucide-react';
import { hasSupabaseConfig, supabase } from './lib/supabase';
import type { TranscriptResult } from './lib/transcript';
import { formatTime, normalizeActorItem } from './lib/transcript';
import { parseYouTubeInput } from './lib/youtube';

type AuthMode = 'signin' | 'signup';
type NoticeTone = 'info' | 'success' | 'error';

type Notice = {
  tone: NoticeTone;
  message: string;
};

type HistoryRow = Record<string, unknown> & {
  id?: string;
  created_at?: string;
  createdAt?: string;
};

const emptyResult: TranscriptResult = {
  videoId: '',
  videoUrl: '',
  videoTitle: 'Paste a YouTube link to start',
  channelName: 'No transcript loaded',
  thumbnail: '',
  language: 'en',
  selectedLanguage: 'en',
  isAutoGenerated: false,
  segmentCount: 0,
  fullText: '',
  segments: []
};

const languageOptions = [
  { value: 'en', label: 'English' },
  { value: 'auto', label: 'Auto-detect' },
  { value: 'es', label: 'Spanish' },
  { value: 'fr', label: 'French' },
  { value: 'de', label: 'German' }
];

function readableDate(value?: string) {
  if (!value) return 'Just now';

  return new Intl.DateTimeFormat(undefined, {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit'
  }).format(new Date(value));
}

function initials(email?: string) {
  return (email?.slice(0, 2) || 'CS').toUpperCase();
}

async function getErrorMessage(error: unknown, fallback: string) {
  if (typeof error === 'object' && error !== null && 'context' in error) {
    const context = (error as { context?: unknown }).context;

    if (context instanceof Response) {
      try {
        const payload = (await context.clone().json()) as { error?: unknown; message?: unknown };
        if (typeof payload.error === 'string') return payload.error;
        if (typeof payload.message === 'string') return payload.message;
      } catch {
        try {
          const text = await context.clone().text();
          if (text) return text;
        } catch {
          return fallback;
        }
      }
    }
  }

  if (error instanceof Error && error.message) return error.message;
  if (typeof error === 'object' && error !== null && 'message' in error) {
    const message = (error as { message?: unknown }).message;
    if (typeof message === 'string') return message;
  }
  return fallback;
}

function normalizeHistoryRow(row: HistoryRow): TranscriptResult {
  const normalized = normalizeActorItem({
    id: row.id,
    videoId: row.video_id ?? row.videoId,
    videoUrl: row.video_url ?? row.videoUrl,
    videoTitle: row.title ?? row.video_title ?? row.videoTitle,
    channelName: row.channel_name ?? row.channelName,
    thumbnail: row.thumbnail_url ?? row.thumbnail,
    language: row.language,
    selectedLanguage: row.selected_language ?? row.selectedLanguage,
    isAutoGenerated: row.is_auto_generated ?? row.isAutoGenerated,
    segmentCount: row.segment_count ?? row.segmentCount,
    fullText: row.transcript ?? row.full_text ?? row.fullText,
    segments: row.segments
  });

  return {
    ...normalized,
    id: row.id,
    createdAt: row.created_at ?? row.createdAt
  };
}

function pickTranscriptPayload(payload: unknown): TranscriptResult {
  const candidate =
    typeof payload === 'object' && payload !== null && 'generation' in payload
      ? (payload as { generation: HistoryRow }).generation
      : typeof payload === 'object' && payload !== null && 'result' in payload
        ? (payload as { result: unknown }).result
      : payload;

  return normalizeHistoryRow((candidate ?? {}) as HistoryRow);
}

export default function App() {
  const [session, setSession] = useState<Session | null>(null);
  const [authLoading, setAuthLoading] = useState(true);
  const [authMode, setAuthMode] = useState<AuthMode>('signin');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [authBusy, setAuthBusy] = useState(false);
  const [authError, setAuthError] = useState('');
  const [showAuthPanel, setShowAuthPanel] = useState(false);
  const [showAccountPanel, setShowAccountPanel] = useState(false);

  const [input, setInput] = useState('');
  const [selectedLanguage, setSelectedLanguage] = useState('en');
  const [inputTouched, setInputTouched] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [notice, setNotice] = useState<Notice | null>(null);
  const [result, setResult] = useState<TranscriptResult>(emptyResult);
  const [history, setHistory] = useState<TranscriptResult[]>([]);
  const [historyLoading, setHistoryLoading] = useState(false);
  const [copied, setCopied] = useState<'full' | 'segments' | null>(null);

  const inputRef = useRef<HTMLInputElement>(null);
  const user: User | undefined = session?.user;
  const parsedInput = useMemo(() => parseYouTubeInput(input), [input]);
  const inputError =
    inputTouched && input.trim() && !parsedInput
      ? 'Use a YouTube watch link, Shorts link, youtu.be link, or 11-character video ID.'
      : '';
  const successfulToday = useMemo(() => {
    const today = new Date().toISOString().slice(0, 10);
    return history.some((item) => item.createdAt?.slice(0, 10) === today);
  }, [history]);

  useEffect(() => {
    if (!hasSupabaseConfig) {
      setAuthLoading(false);
      setNotice({
        tone: 'error',
        message: 'Supabase env vars are missing. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.'
      });
      return;
    }

    let mounted = true;

    supabase.auth.getSession().then(({ data }) => {
      if (!mounted) return;
      setSession(data.session);
      setAuthLoading(false);
      setShowAuthPanel(!data.session);
    });

    const {
      data: { subscription }
    } = supabase.auth.onAuthStateChange((_event, nextSession) => {
      setSession(nextSession);
      setShowAuthPanel(!nextSession);
      if (nextSession) {
        setNotice({ tone: 'success', message: 'Signed in. Your paste stayed right where it was.' });
      }
    });

    return () => {
      mounted = false;
      subscription.unsubscribe();
    };
  }, []);

  useEffect(() => {
    if (!session) {
      setHistory([]);
      return;
    }

    void loadHistory();
  }, [session]);

  async function loadHistory() {
    if (!session) return;

    setHistoryLoading(true);
    const { data, error } = await supabase
      .from('transcript_generations')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(12);

    setHistoryLoading(false);

    if (error) {
      setNotice({ tone: 'error', message: `History did not load: ${error.message}` });
      return;
    }

    const rows = (data ?? []) as HistoryRow[];
    const items = rows.map(normalizeHistoryRow);
    setHistory(items);
    if (!result.fullText && items[0]) setResult(items[0]);
  }

  async function handleAuth(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setAuthError('');

    if (!hasSupabaseConfig) {
      setAuthError('Supabase is not configured yet.');
      return;
    }

    if (password.length < 6) {
      setAuthError('Password must be at least 6 characters.');
      return;
    }

    setAuthBusy(true);
    const response =
      authMode === 'signin'
        ? await supabase.auth.signInWithPassword({ email, password })
        : await supabase.auth.signUp({ email, password });
    setAuthBusy(false);

    if (response.error) {
      setAuthError(response.error.message);
      return;
    }

    setPassword('');
    setShowAuthPanel(false);
    setNotice({
      tone: 'success',
      message:
        authMode === 'signup'
          ? 'Account created. Check your inbox if email confirmation is enabled.'
          : 'Welcome back.'
    });
  }

  async function signOut() {
    await supabase.auth.signOut();
    setResult(emptyResult);
    setHistory([]);
    setShowAccountPanel(false);
    setNotice({ tone: 'info', message: 'Signed out. Your local result view is cleared.' });
  }

  async function generateTranscript(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setInputTouched(true);
    setNotice(null);

    if (!parsedInput) {
      inputRef.current?.focus();
      return;
    }

    if (!session) {
      setShowAuthPanel(true);
      setNotice({ tone: 'info', message: 'Create or sign in to use your free daily generation.' });
      return;
    }

    setGenerating(true);
    const { data, error } = await supabase.functions.invoke('generate-transcript', {
      body: {
        input: parsedInput.canonicalUrl,
        language: selectedLanguage === 'auto' ? 'en' : selectedLanguage
      }
    });
    setGenerating(false);

    if (error) {
      setNotice({
        tone: 'error',
        message: await getErrorMessage(error, 'Transcript generation failed. Try a different video.')
      });
      return;
    }

    const nextResult = pickTranscriptPayload(data);
    setResult(nextResult);
    setHistory((items) => [
      { ...nextResult, createdAt: new Date().toISOString() },
      ...items.filter((item) => item.videoId !== nextResult.videoId)
    ]);
    setNotice({ tone: 'success', message: 'Transcript is ready to copy, skim, or revisit later.' });
  }

  async function copyText(kind: 'full' | 'segments') {
    const text =
      kind === 'segments'
        ? result.segments.map((segment) => `${formatTime(segment.start)} ${segment.text}`).join('\n')
        : result.fullText;

    if (!text) return;

    await navigator.clipboard.writeText(text);
    setCopied(kind);
    window.setTimeout(() => setCopied(null), 1800);
  }

  const activeResult = result.fullText ? result : emptyResult;

  return (
    <div className="app-shell">
      <header className="topbar">
        <a className="skip-link" href="#generator">
          Skip to generator
        </a>
        <div className="brand-lockup" aria-label="ClipScript home">
          <span className="brand-mark">
            <ReceiptText aria-hidden="true" size={22} />
          </span>
          <div>
            <p className="eyebrow">ClipScript</p>
            <h1>One link in. Clean transcript out.</h1>
          </div>
        </div>

        <div className="topbar-actions">
          <div className="offer-pill">
            <Sparkles aria-hidden="true" size={16} />
            <span>1 free generation daily</span>
          </div>
          {user ? (
            <button className="avatar-button" type="button" onClick={() => setShowAccountPanel(true)}>
              <span>{initials(user.email)}</span>
              <UserRound aria-hidden="true" size={18} />
            </button>
          ) : (
            <button className="secondary-button" type="button" onClick={() => setShowAuthPanel(true)}>
              <UserRound aria-hidden="true" size={18} />
              Sign in
            </button>
          )}
        </div>
      </header>

      <main className="workspace">
        <aside className="history-rail" aria-label="Transcript history">
          <div className="rail-heading">
            <div>
              <p className="eyebrow">History</p>
              <h2>Recent pulls</h2>
            </div>
            <History aria-hidden="true" size={20} />
          </div>

          {historyLoading ? (
            <div className="mini-state">
              <Loader2 className="spin" aria-hidden="true" size={18} />
              Loading history
            </div>
          ) : history.length ? (
            <div className="history-list">
              {history.map((item) => (
                <button
                  className={`history-item ${item.videoId === result.videoId ? 'is-active' : ''}`}
                  type="button"
                  key={`${item.videoId}-${item.createdAt ?? item.id}`}
                  onClick={() => setResult(item)}
                >
                  <span className="history-title">{item.videoTitle}</span>
                  <span className="history-meta">
                    {readableDate(item.createdAt)} - {item.segmentCount || item.segments.length} segments
                  </span>
                </button>
              ))}
            </div>
          ) : (
            <div className="empty-block">
              <Clock3 aria-hidden="true" size={20} />
              <p>Your generated transcripts will stack here after sign-in.</p>
            </div>
          )}
        </aside>

        <section className="generator-column" id="generator" aria-labelledby="generator-title">
          <div className="status-strip">
            <span className={session ? 'dot is-live' : 'dot'} aria-hidden="true" />
            {authLoading
              ? 'Checking session'
              : session
                ? successfulToday
                  ? 'Daily free credit used'
                  : 'Daily free credit ready'
                : 'Sign in to generate'}
          </div>

          <form className="generator-panel" onSubmit={generateTranscript} noValidate>
            <div className="panel-kicker">
              <Play aria-hidden="true" size={18} />
              Single-link generator
            </div>
            <h2 id="generator-title">Paste the video everyone keeps quoting.</h2>

            <label className="field-label" htmlFor="youtube-input">
              YouTube link or video ID
            </label>
            <div className={`input-wrap ${inputError ? 'has-error' : ''}`}>
              <input
                ref={inputRef}
                id="youtube-input"
                value={input}
                onChange={(event) => setInput(event.target.value)}
                onBlur={() => setInputTouched(true)}
                placeholder="https://youtu.be/dQw4w9WgXcQ"
                inputMode="url"
                autoComplete="url"
                aria-describedby="youtube-help youtube-error"
                aria-invalid={Boolean(inputError)}
              />
              {parsedInput ? <Check className="input-icon ok" aria-hidden="true" size={20} /> : null}
            </div>
            <p className="field-help" id="youtube-help">
              Works with watch, Shorts, youtu.be links, and raw video IDs.
            </p>
            {inputError ? (
              <p className="field-error" id="youtube-error" role="alert">
                <AlertCircle aria-hidden="true" size={16} />
                {inputError}
              </p>
            ) : null}

            <div className="form-row">
              <label className="select-label" htmlFor="language-select">
                Language
                <select
                  id="language-select"
                  value={selectedLanguage}
                  onChange={(event) => setSelectedLanguage(event.target.value)}
                >
                  {languageOptions.map((option) => (
                    <option value={option.value} key={option.value}>
                      {option.label}
                    </option>
                  ))}
                </select>
              </label>

              <button className="primary-button" type="submit" disabled={generating || authLoading}>
                {generating ? (
                  <Loader2 className="spin" aria-hidden="true" size={18} />
                ) : (
                  <ArrowRight aria-hidden="true" size={18} />
                )}
                {generating ? 'Generating' : 'Generate'}
              </button>
            </div>

            {notice ? (
              <div className={`notice ${notice.tone}`} role={notice.tone === 'error' ? 'alert' : 'status'}>
                {notice.tone === 'error' ? (
                  <AlertCircle aria-hidden="true" size={18} />
                ) : (
                  <BadgeCheck aria-hidden="true" size={18} />
                )}
                {notice.message}
              </div>
            ) : null}
          </form>

          <div className="account-card">
            <ShieldCheck aria-hidden="true" size={22} />
            <div>
              <p className="eyebrow">Account</p>
              <h3>{user?.email ?? 'No account connected'}</h3>
              <p>
                {session
                  ? 'Saved history is active and tied to your Supabase session.'
                  : 'Sign in once, then your daily free run and history follow you.'}
              </p>
            </div>
            <button className="icon-button" type="button" onClick={() => setShowAccountPanel(true)}>
              <Settings2 aria-hidden="true" size={18} />
              <span className="sr-only">Open account panel</span>
            </button>
          </div>
        </section>

        <section className="result-panel" aria-labelledby="result-title">
          <div className="result-head">
            {activeResult.thumbnail ? (
              <img src={activeResult.thumbnail} alt="" className="thumb" />
            ) : (
              <div className="thumb placeholder">
                <PanelRight aria-hidden="true" size={28} />
              </div>
            )}
            <div>
              <p className="eyebrow">{activeResult.channelName}</p>
              <h2 id="result-title">{activeResult.videoTitle}</h2>
              <div className="result-meta">
                <span>{activeResult.language.toUpperCase()}</span>
                <span>{activeResult.segmentCount || activeResult.segments.length} segments</span>
                {activeResult.isAutoGenerated ? <span>Auto captions</span> : null}
              </div>
            </div>
          </div>

          <div className="copy-row" aria-label="Transcript actions">
            <button
              className="secondary-button"
              type="button"
              onClick={() => copyText('full')}
              disabled={!result.fullText}
            >
              {copied === 'full' ? <Check aria-hidden="true" size={18} /> : <Copy aria-hidden="true" size={18} />}
              {copied === 'full' ? 'Copied' : 'Copy transcript'}
            </button>
            <button
              className="secondary-button lime"
              type="button"
              onClick={() => copyText('segments')}
              disabled={!result.segments.length}
            >
              {copied === 'segments' ? (
                <Check aria-hidden="true" size={18} />
              ) : (
                <Clock3 aria-hidden="true" size={18} />
              )}
              {copied === 'segments' ? 'Copied' : 'Copy timestamps'}
            </button>
            {activeResult.videoUrl ? (
              <a className="text-link" href={activeResult.videoUrl} target="_blank" rel="noreferrer">
                Open video
                <ExternalLink aria-hidden="true" size={16} />
              </a>
            ) : null}
          </div>

          {result.fullText ? (
            <>
              <article className="transcript-box" aria-label="Full transcript">
                {result.fullText}
              </article>
              <div className="segment-list" aria-label="Timestamped transcript segments">
                {result.segments.slice(0, 80).map((segment) => (
                  <div className="segment" key={`${segment.start}-${segment.text}`}>
                    <span>{formatTime(segment.start)}</span>
                    <p>{segment.text}</p>
                  </div>
                ))}
              </div>
            </>
          ) : (
            <div className="empty-result">
              <ReceiptText aria-hidden="true" size={42} />
              <h3>Your transcript lands here.</h3>
              <p>Paste one link, generate once, then copy the exact words without scrubbing the video.</p>
            </div>
          )}
        </section>
      </main>

      {showAuthPanel ? (
        <div className="side-panel-layer" role="presentation">
          <section className="side-panel" aria-labelledby="auth-title">
            <button className="icon-button close" type="button" onClick={() => setShowAuthPanel(false)}>
              <X aria-hidden="true" size={18} />
              <span className="sr-only">Close auth panel</span>
            </button>
            <p className="eyebrow">Auth</p>
            <h2 id="auth-title">{authMode === 'signin' ? 'Sign back in' : 'Make your pass'}</h2>
            <p className="panel-copy">One free successful transcript per day. Your history stays attached to this login.</p>

            <form className="auth-form" onSubmit={handleAuth} noValidate>
              <label htmlFor="email">Email</label>
              <input
                id="email"
                type="email"
                value={email}
                onChange={(event) => setEmail(event.target.value)}
                autoComplete="email"
                required
              />

              <label htmlFor="password">Password</label>
              <input
                id="password"
                type="password"
                value={password}
                onChange={(event) => setPassword(event.target.value)}
                autoComplete={authMode === 'signin' ? 'current-password' : 'new-password'}
                minLength={6}
                required
              />

              {authError ? (
                <p className="field-error" role="alert">
                  <AlertCircle aria-hidden="true" size={16} />
                  {authError}
                </p>
              ) : null}

              <button className="primary-button full" type="submit" disabled={authBusy || !email || !password}>
                {authBusy ? <Loader2 className="spin" aria-hidden="true" size={18} /> : <ArrowRight size={18} />}
                {authMode === 'signin' ? 'Sign in' : 'Create account'}
              </button>
            </form>

            <button
              className="switch-auth"
              type="button"
              onClick={() => {
                setAuthMode(authMode === 'signin' ? 'signup' : 'signin');
                setAuthError('');
              }}
            >
              {authMode === 'signin' ? 'Need an account? Sign up' : 'Already have one? Sign in'}
            </button>
          </section>
        </div>
      ) : null}

      {showAccountPanel ? (
        <div className="side-panel-layer" role="presentation">
          <section className="side-panel account" aria-labelledby="account-title">
            <button className="icon-button close" type="button" onClick={() => setShowAccountPanel(false)}>
              <X aria-hidden="true" size={18} />
              <span className="sr-only">Close account panel</span>
            </button>
            <p className="eyebrow">Account</p>
            <h2 id="account-title">{user?.email ?? 'Guest mode'}</h2>
            <div className="account-stat">
              <span>Daily credit</span>
              <strong>{successfulToday ? 'Used' : 'Ready'}</strong>
            </div>
            <div className="account-stat">
              <span>Plan</span>
              <strong>Free beta</strong>
            </div>
            <div className="account-stat">
              <span>Offer expiry</span>
              <strong>Rolling 24h UTC</strong>
            </div>
            {session ? (
              <button className="danger-button" type="button" onClick={signOut}>
                <LogOut aria-hidden="true" size={18} />
                Sign out
              </button>
            ) : (
              <button className="primary-button full" type="button" onClick={() => setShowAuthPanel(true)}>
                <UserRound aria-hidden="true" size={18} />
                Sign in
              </button>
            )}
          </section>
        </div>
      ) : null}
    </div>
  );
}
